////
Licensed to the Apache Software Foundation (ASF) under one or more
contributor license agreements.  See the NOTICE file distributed with
this work for additional information regarding copyright ownership.
The ASF licenses this file to You under the Apache License, Version 2.0
(the "License"); you may not use this file except in compliance with
the License.  You may obtain a copy of the License at

  http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
////
[[meetings]]
Meetings
========

November 23, 2015
-----------------

The meeting was scheduled for 12:00pm EST, started at 12:05pm when sufficient attendance to constitute a quorum was
reached and was held via Google Hangout hosted by Marko Rodriguez. Meeting adjourned at 2:35pm EST.

*Committers/PPMC Members*

* Daniel Kuppitz
* Stephen Mallette
* Dylan Millikin
* Jason Plurad
* Marko Rodriguez
* Ted Wilmes

*Guests*

_None_

*Minutes*

* Performed a full review of the list of unresolved tickets in JIRA. The summary of the changes can be found below.
Note that releases and assignments made today are not meant to be set in stone. The assignments could change given
community discussion or unforeseen events.
* Decided to add version `3.2.0-incubating` to JIRA.  This version was added to help better categorize the available
issues. It was explicitly decided that no development was expected to be performed on these issue at this time and
that we would wait until `3.1.1-incubating` was released before thinking too hard on that body of work.  This
decision means that the `master` branch will continue to be the current branch of development for the time being
and be bound to `3.1.x` line of code.
* Discussed use of JIRA dependency links to show "blockers" and dependencies among different JIRA tickets.
* Discussed a target date for upcoming releases:
** `3.1.1-incubating` - February 1, 2016
** `3.2.0-incubating` - May, 1, 2016

The following tickets were assigned to `3.1.1-incubating`:

[width="100%",cols="2,5,2",options="header"]
|=========================================================
|ID |Description |Type
|TINKERPOP-379 |MessageScope.Local.setStaticMessage(M msg) |Improvement
|TINKERPOP-659 |GraphConfiguration Class |Improvement
|TINKERPOP-736 |Automatic Traversal rewriting |Improvement
|TINKERPOP-763 |IsStep broken when profiling is enabled. |Bug
|TINKERPOP-818 |Consider a P.instanceOf() |Improvement
|TINKERPOP-824 |Do we need runtime BigDecimal in more places? |Improvement
|TINKERPOP-842 |MapReduceHelper should sort respective of the number of reduce tasks |Improvement
|TINKERPOP-859 |Provide a more general way to set log levels in plugins |Improvement
|TINKERPOP-860 |Bindings applied to the PluginAcceptor should appear to Gremlin Server |Improvement
|TINKERPOP-882 |Develop a less error prone way for rewriting strategies |Improvement
|TINKERPOP-886 |Allow any GraphReader/Writer to be persistence engine for TinkerGraph |Improvement
|TINKERPOP-891 |Re-examine Sandboxing Abstractions |Improvement
|TINKERPOP-893 |Validate dependency grabs that have TinkerPop dependencies |Improvement
|TINKERPOP-912 |Improve the ability to embed Gremlin Server with Channelizer injection |Improvement
|TINKERPOP-920 |Test case needed for ensuring same cardinality for key. |Improvement
|TINKERPOP-927 |bin/publish-docs.sh should only upload diffs. |Improvement
|TINKERPOP-930 |Tie Alias to Transaction Manager in Gremlin Server |Improvement
|TINKERPOP-932 |Add ability to cancel script execution associated with a Gremlin Server Session |Improvement
|TINKERPOP-937 |Move the implementations sections of the primary documentation to "provider tutorials." |Improvement
|TINKERPOP-938 |Add a "clear SNAPSHOT jars" section to the process-docs.sh. |Improvement
|TINKERPOP-939 |Neo4jGraph should support HighAvailability (Neo4jHA). |Improvement
|TINKERPOP-941 |Improve error message for wrong order().by() arguments |Improvement
|TINKERPOP-943 |Warn if Gremlin Server is running prior to generating docs |Improvement
|TINKERPOP-951 |Barrier steps provide unexpected results in Gremlin OLAP |Bug
|TINKERPOP-954 |Consistent test directory usage |Improvement
|TINKERPOP-956 |Connection errors tend to force a complete close of the channel |Improvement
|TINKERPOP-958 |Improve usability of .profile() step. |Improvement
|TINKERPOP-964 |Test XXXGraphComputer on a Hadoop2 cluster (non-pseudocluster). |Improvement
|TINKERPOP-967 |Support nested-repeat() structures |Improvement
|TINKERPOP-973 |BLVP shouldn't clear configuration properties |Bug
|TINKERPOP-976 |Fail earlier if invalid version is supplied in validate-distribution.sh |Bug
|TINKERPOP-978 |Native TinkerGraph Serializers for GraphSON |Improvement
|TINKERPOP-979 |ComputerVerificationStrategy not picking up Order local traversal |Bug
|TINKERPOP-980 |Add a service script or daemon mode in the distribution |Improvement
|TINKERPOP-981 |Deprecate support for credentialsDbLocation in Gremlin Server Config |Improvement
|TINKERPOP-983 |Provide a way to track open Graph instances in tests |Improvement
|TINKERPOP-984 |Use GraphProvider for id conversion in Groovy Environment test suite |Improvement
|TINKERPOP-986 |Manage binary LICENSE/NOTICE files with bin/checkLicenseNotice.sh |Improvement
|TINKERPOP-988 |SparkGraphComputer.submit shouldn't use ForkJoinPool.commonPool |Improvement
|=========================================================

The following items were identified for `3.2.0-incubating`:

[width="100%",cols="2,5,2",options="header"]
|=========================================================
|ID |Description |Type
|TINKERPOP-331 |TraverserConverterStep (proposal) |Improvement
|TINKERPOP-620 |Commutative Step Marker interface |Improvement
|TINKERPOP-669 |Consider Required TraversalStrategies |Improvement
|TINKERPOP-691 |TP3 is too prescriptive in exception |Improvement
|TINKERPOP-740 |Serializer Handshake |Improvement
|TINKERPOP-743 |Support "barrier syntax" in step labels. |Improvement
|TINKERPOP-761 |Some basic mathematical functions / steps |Improvement
|TINKERPOP-786 |Patterns for DSL Development |Improvement
|TINKERPOP-789 |Choose then Enforce Semantics for Graph.close() |Improvement
|TINKERPOP-790 |Implement AutoCloseable on TraversalSource |Improvement
|TINKERPOP-800 |[Proposal] Domain/Range checking during traversal construction. |Improvement
|TINKERPOP-813 |[Proposal] Make the Gremlin Graph Traversal Machine and Instruction Set Explicit |Improvement
|TINKERPOP-819 |Mapping Cardinality Interface |Improvement
|TINKERPOP-831 |How should OLAP treat Collection<Element> objects? No contract is specified. |Bug
|TINKERPOP-844 |PropertyMapStep should reuse PropertiesStep |Improvement
|TINKERPOP-864 |Operator.mean would be nice. |Improvement
|TINKERPOP-871 |RuntimeStrategy as the general model for all such execution time rewrites/re-orders |Improvement
|TINKERPOP-872 |Remove GroupCountStep in favor of new Reduce-based GroupStep |Improvement
|TINKERPOP-873 |FoldStep should default to using BulkSet for efficiency. |Improvement
|TINKERPOP-878 |Refactor Gremlin Server integration tests to be Client parameterized |Improvement
|TINKERPOP-889 |Support for partitioned vertices in GraphComputer |Improvement
|TINKERPOP-890 |Remove the concept of branch/ package. |Improvement
|TINKERPOP-919 |Features needs to specify whether 2 vertex properties with same key/value is allowed. |Improvement
|TINKERPOP-940 |Convert LocalTraversals to MatchSteps in OLAP and Solve the StarGraph Problem |Improvement
|TINKERPOP-942 |Use EventStrategy to solve OLAP bulk mutation of OLTP. |Improvement
|TINKERPOP-944 |Consider deprecating or better enforcing Graph.Exceptions.elementNotFound |Improvement
|TINKERPOP-946 |Traversal respecting Thread.interrupt() |Improvement
|TINKERPOP-947 |Enforce semantics of threaded transactions as manual |Improvement
|TINKERPOP-960 |Add a Bulk class which is used by Traverser |Improvement
|TINKERPOP-962 |Provide "vertex query" selectivity when importing data in OLAP. |Improvement
|TINKERPOP-963 |SubgraphTraversalAnalyzer to determine what is really required from a traversal. |Improvement
|TINKERPOP-966 |Support reversible traversals in MatchStep (and respective MatchAlgorithms) |Improvement
|TINKERPOP-969 |respawn |Improvement
|TINKERPOP-971 |TraversalSource should be fluent like GraphComputer |Improvement
|TINKERPOP-974 |Saving headless traversals for reuse (clone Iterator Fun) |Improvement
|TINKERPOP-982 |valuesDecr, valuesIncr, keysDecr, and valuesDecr is lame. |Improvement
|=========================================================

The following issues were simply closed during review - the reasons for closing can be found in the comments of the
issues themselves:

[width="100%",cols="2,5,2",options="header"]
|=========================================================
|ID |Description |Type
|TINKERPOP-375 |Better Methods for Managing ClassPath for Plugins |Improvement
|TINKERPOP-487 |User Supplied Ids and IO |Improvement
|TINKERPOP-509 |Subgraph support for VertexProgram |
|TINKERPOP-604 |DetachedEdge.attach(Vertex) is too slow. |Improvement
|TINKERPOP-795 |Provide Traverser.setPath() |Improvement
|TINKERPOP-862 |Add a TraversalSourceStrategy that provides "locked" values. |Improvement
|TINKERPOP-894 |Shorthand for install of TinkerPop dependencies |Improvement
|TINKERPOP-936 |Check feature requirements before opening graph during tests |Improvement
|=========================================================

October 29, 2015
----------------

The meeting was scheduled for 1:00pm EST, started on time and was held via Google Hangout hosted by Stephen Mallette.
Meeting adjourned at 1:45pm EST.

*Committers/PPMC Members*

* Daniel Kuppitz
* Stephen Mallette
* Marko Rodriguez

*Guests*

_None_

*Minutes*

* Reviewed the scope of 3.1.0-incubating in JIRA in the context of the upcoming release date on November 16, 2015.
* It was noted that with the new one week code freeze policy that the real cut-off date for work is November 9, 2015.
* There was general consensus on the call that work should be accomplished in such a way that the code review process
not drag into the code freeze time period.  In other words, pull requests to the release branch should be completed
well ahead of the 9th.

Upon review of the tickets in JIRA assigned to 3.1.0-incubating, the following were removed from the 3.1.0-incubating
roadmap:

[width="100%",cols="2,5,5",options="header"]
|=========================================================
|ID |Description |Removal Reasoning
|TINKERPOP-891 |Re-examine Sandboxing Abstractions |Low priority and time limitations.
|TINKERPOP-890 |Remove the concept of branch/ package. |Awaiting step library definition in 3.2.0-incubating.
|TINKERPOP-873 |FoldStep should default to using BulkSet for efficiency. |Awaiting step library definition in 3.2.0-incubating.
|TINKERPOP-864 |Operator.mean would be nice. |Awaiting step library definition in 3.2.0-incubating.
|TINKERPOP-862 |Add a TraversalSourceStrategy that provides "locked" values. |Low priority and time limitations.
|TINKERPOP-854 |Remove PropertyMapStep in favor of multi-instruction construction. |Non-trivial given time limitations.
|TINKERPOP-789 |Choose then Enforce Semantics for Graph.close() |Non-trivial given time limitations.
|TINKERPOP-768 |MatchStep in OLAP should be smart about current vertex. |Non-trivial given time limitations.
|TINKERPOP-705 |Make use of a MemoryRDD instead of Accumulators in SparkGraphComputer? |Non-trivial given time limitations.
|TINKERPOP-659 |GraphConfiguration Class |Non-trivial given time limitations.
|TINKERPOP-623 |More output for OLAP jobs |Not clearly defined given time limitations.
|TINKERPOP-620 |Commutative Step Marker interface |Awaiting step library definition in 3.2.0-incubating
|TINKERPOP-550 |Gremlin IO needs to support both OLTP and OLAP naturally. |Not clearly defined given time limitations.
|TINKERPOP-479 |Consider Providing "getOrCreate" Functionality |Not clearly defined given time limitations.
|=========================================================