version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/gremlin-dotnet"
    schedule:
      interval: "monthly"
    target-branch: "master"
    labels:
      - ".NET"
      - "dependencies"
    groups:
      dotnet-security:
        applies-to: security-updates
        patterns: ["*"]
    ignore:
      - update-types: [ "version-update:semver-patch", "version-update:semver-minor" ]
        dependency-name: "*"
  - package-ecosystem: "pip"
    directory: "/gremlin-python/src/main/python"
    schedule:
      interval: "monthly"
    target-branch: "master"
    labels:
      - "python"
      - "dependencies"
    groups:
      python-security:
        applies-to: security-updates
        patterns: ["*"]
    ignore:
      - update-types: [ "version-update:semver-patch", "version-update:semver-minor" ]
        dependency-name: "*"
  - package-ecosystem: "npm"
    directory: "/gremlin-js"
    schedule:
      interval: "monthly"
    target-branch: "master"
    labels:
      - "javascript"
      - "dependencies"
    groups:
      js-security-runtime:
        applies-to: security-updates
        dependency-type: production
        patterns: ["*"]
      js-security-dev:
        applies-to: security-updates
        dependency-type: development
        patterns: ["*"]
    ignore:
      - update-types: ["version-update:semver-patch", "version-update:semver-minor"]
        dependency-name: "*"
  - package-ecosystem: "npm"
    directory: "/docs/gremlint"
    schedule:
      interval: "monthly"
    target-branch: "master"
    labels:
      - "site"
      - "dependencies"
    groups:
      site-security-runtime:
        applies-to: security-updates
        dependency-type: production
        patterns: ["*"]
      site-security-dev:
        applies-to: security-updates
        dependency-type: development
        patterns: ["*"]
    ignore:
      - update-types: [ "version-update:semver-patch", "version-update:semver-minor" ]
        dependency-name: "*"
  - package-ecosystem: "npm"
    directory: "/docs/gremlator"
    schedule:
      interval: "monthly"
    target-branch: "master"
    labels:
      - "site"
      - "dependencies"
    groups:
      site-security-runtime:
        applies-to: security-updates
        dependency-type: production
        patterns: ["*"]
      site-security-dev:
        applies-to: security-updates
        dependency-type: development
        patterns: ["*"]
    ignore:
      - update-types: [ "version-update:semver-patch", "version-update:semver-minor" ]
        dependency-name: "*"
  - package-ecosystem: "gomod"
    directory: "/gremlin-go"
    schedule:
      interval: "monthly"
    target-branch: "master"
    labels:
      - "go"
      - "dependencies"
    groups:
      go-security:
        applies-to: security-updates
        patterns: ["*"]
    ignore:
      - update-types: [ "version-update:semver-patch", "version-update:semver-minor" ]
        dependency-name: "*"
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "monthly"
    target-branch: "master"
    labels:
      - "java"
      - "dependencies"
    groups:
      java-security:
        applies-to: security-updates
        patterns: ["*"]
    ignore:
      - update-types: [ "version-update:semver-patch", "version-update:semver-minor" ]
        dependency-name: "*"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    target-branch: "3.7-dev"
    labels:
      - "dependencies"
