github:
  description: "Apache TinkerPop - a graph computing framework"
  homepage: https://tinkerpop.apache.org/
  dependabot_alerts: false
  dependabot_updates: false
  del_branch_on_merge: true
  labels:
    - tinkerpop
    - gremlin
    - graph
    - graphdb
    - graph-database
    - gremlin-server
    - apache