////
Licensed to the Apache Software Foundation (ASF) under one or more
contributor license agreements.  See the NOTICE file distributed with
this work for additional information regarding copyright ownership.
The ASF licenses this file to You under the Apache License, Version 2.0
(the "License"); you may not use this file except in compliance with
the License.  You may obtain a copy of the License at

  http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
////

== Repository Fork
This repository aims for solving the https://issues.apache.org/jira/browse/TINKERPOP-2137 issue.
Gremlin-Javascript can't be run in Browsers, because the apache dependencies rely on server-side packages (e.g. crypto, ws).
This repository removes these dependencies, but with some consequencies:
 * you can't use WS config parameters to configure KeyStore, Headers or other WebSocket configs. The new WebSocket class takes only URL, if security is required, it must work as it should work in any browser (signed certificates etc...).
 
 If you need to know, how to setup SSL for your Gremlin Server (e.g. on Windows), use this guide: https://gist.github.com/szydan/dc19d1c833b3125a9c8fa4f6daad7f29
 Afterwards the gremlin-javascript from browser should work.
