////
Licensed to the Apache Software Foundation (ASF) under one or more
contributor license agreements.  See the NOTICE file distributed with
this work for additional information regarding copyright ownership.
The ASF licenses this file to You under the Apache License, Version 2.0
(the "License"); you may not use this file except in compliance with
the License.  You may obtain a copy of the License at

  http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
////
== TinkerPop4

* *java*: Apache TinkerPop for Java
** *core*: A collection of machine and language components
** *data*
*** *graph*: Operators for processing property graph data.
**** *neo4j*: A Neo4j implementation of the graph primitives
**** *tinkergraph*: A TinkerGraph implementation of the graph primitives
** *machine*
*** *pipes*: Java iterator implementation of the traversal machine
*** *rxjava*: RxJava implementation of the traversal machine
*** *beam*: Apache Beam implementation of the traversal machine
*** *akka*: Akka implementation of the traversal machine
** *language*
*** *variant*
**** *groovy*: Groovy implementation of the Gremlin language
**** *scala*: Python implementation of the Gremlin language
*** *distinct*
**** *sparql*: A SPARQL to Gremlin bytecode compiler
**** *sql*: An SQL to Gremlin bytecode compiler
**** *cypher*: A Cypher to Gremlin bytecode compiler
* *test*: language test suite
* *python*: Apache TinkerPop for Python
* *dotnet*: Apache TinkerPop for C#
* *javascript*: Apache TinkerPop for JavaScript