////
Licensed to the Apache Software Foundation (ASF) under one or more
contributor license agreements.  See the NOTICE file distributed with
this work for additional information regarding copyright ownership.
The ASF licenses this file to You under the Apache License, Version 2.0
(the "License"); you may not use this file except in compliance with
the License.  You may obtain a copy of the License at

  http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
////
= Gremlin DSL

This is a starter project that demonstrates how a basic
link:http://tinkerpop.apache.org/docs/${project.version}/reference/#dsl[Domain Specific Language] (DSL) project is
structured with Java and Maven. The DSL is built to work with the TinkerPop "modern" toy graph. Please see the unit
tests in `SocialDslTest` for actual DSL usage.

== Prerequisites

* Java 11
* link:https://maven.apache.org/[Maven 3.3+]

== Building and Running

[source,text]
mvn clean install
