////
Licensed to the Apache Software Foundation (ASF) under one or more
contributor license agreements.  See the NOTICE file distributed with
this work for additional information regarding copyright ownership.
The ASF licenses this file to You under the Apache License, Version 2.0
(the "License"); you may not use this file except in compliance with
the License.  You may obtain a copy of the License at

  http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.

////

[[graphbinary]]
= GraphBinary

GraphBinary is a binary serialization format suitable for object trees, designed to reduce serialization
overhead on both the client and the server, as well as limiting the size of the payload that is transmitted over the
wire.

It describes arbitrary object graphs with a fully-qualified format:

[source]
----
{type_code}{type_size}{value}
----

Where:

* `{type_code}` is a single unsigned byte representing the type number. Values that are smaller than 0x40 are fixed
length.
** If the two MSB are 0b01 then this `{type_code}` is followed by a 1 byte `{type_size}` .
** If the two MSB are 0b10 then this `{type_code}` is followed by a 2 byte `{type_size}` .
** If the two MSB are 0b11 then this `{type_code}` is followed by a 4 byte `{type_size}` .
* `{type_size}` is an optional sequence of bytes that describes the length of {value} in bytes. This only exists for
variable-length types (type_code > 0x40).
* `{value}` is a sequence of bytes which content is determined by the type.

All encodings are big-endian.

Quick examples, using hexadecimal notation to represent each byte:

- `03 00 00 00 01`: a 32-bit integer number, that represents the decimal number 1. It’s composed by the
type_code `0x01`, and empty flag value `0x00` and four bytes to describe the value.
- `03 00 00 00 ff`: a 32-bit integer, representing the number 256.
- `04 00 00 00 00 00 00 00 01`: a 64-bit integer number 1. It’s composed by the type_code `0x02`, empty flags and
eight bytes to describe the value.

== Version 4.0

=== Forward Compatibility

The serialization format supports new types being added without the need to introduce a new version.

Changes to existing types require new revision.

=== Changes compared to GraphBinary 1

- The byte ordering is now a TLV system (type, length, value). The length is required before the value so deserializers
know how many bytes are potentially needed to be skipped if it encounters an unknown type. GraphBinary1 employed a
type-value system instead where each type had to be defined in the specification in order for the deserializer
to understand how to deserialize it.
- GraphBinary 4 attempts to reduce the size further by reducing the {type_size} bytes. This allows for better packing
and allows container types like list to contain fully qualified types rather than just their values.
- {type_info} and {value_flag} is removed from each type reducing the size by two bytes. {type_info} was only used for
custom types which have been removed. {value_flag} shouldn't be used because it breaks compatibility, deserializers
won't know how to handle new flags. This, however, means there will be more types like BulkedList and OrderedMap.
- GraphBinary 4 introduces the concept of a "TinkerPop Defined Type". These are types that include field numbers that
are used for identifying changes to existing types.
- There is only a single null type. The addition of field numbers reduces the need to have a null value_flag.
- There are size limitations compared to GraphBinary 1. Because the length of the data needs to be known upfront and
the maximum length is a 4-byte integer, this means every type will effectively be limited to 2^32-1 in size. This also
means that the full object needs to be fully serializable in memory in order to get the total length. This may lead to
increased memory consumption during serialization.

=== Data Type Codes

==== Core Types

- `0x00`: Unspecified null object
- `0x01`: Byte
- `0x02`: Short
- `0x03`: Int
- `0x04`: Long
- `0x05`: Float
- `0x06`: Double
- `0x07`: Binary
- `0x08`: UUID
- `0x09`: Char
- `0x0A`: Boolean
- `0x80`: 16-bit List
- `0xC0`: 32-bit List
- `0x84`: 16-bit BulkedList
- `0xD3`: 32-bit BulkedList
- `0x81`: 16-bit Map
- `0xC1`: 32-bit Map
- `0x85`: 16-bit OrderedMap
- `0xD4`: 32-bit OrderedMap
- `0x82`: 16-bit Set
- `0xC2`: 32-bit Set
- `0x83`: 16-bit String
- `0xC3`: 32-bit String
- `0xC4`: BigInteger
- `0xC5`: BigDecimal

==== TinkerPop Defined Types

Each of the following "TinkerPop Defined Types" may have their formats change. In order to accomdate change,
the {value} portion of these types should contain a field number. It would look like ({field_number}{field_value})*

- `0x0B`: Marker
- `0x0C`: Direction
- `0x0D`: T
- `0x0E`: Duration
- `0x0F`: DateTime
- `0xCE`: Edge
- `0xCB`: Path
- `0xCC`: Property
- `0xCD`: Vertex
- `0xCE`: VertexProperty
- `0xCF`: Tree
- `0xD0`: TinkerGraph
- `0xD1`: CompositePDT
- `0xD2`: PrimitivePDT

=== Null handling

Nulls are represented by the type 0x00.

=== Data Type Formats

==== Int

`{value}` Format: 4-byte two's complement integer.

Example values:

- `00 00 01`: 32-bit integer number 1.

==== 16-bit String

`{value}` Format: `{text_value}`

Where:

- `{text_value}` is a sequence of bytes representing the string value in UTF8 encoding.

Example values

- `83 00 03 61 62 63`: the string 'abc'.
- `83 00 04 61 62 63 64`: the string 'abcd'.
- `83 00 00`: the empty string ''.

==== 32-bit String

`{value}` Format: `{text_value}`

Where:

- `{length}` is an `Int` describing the byte length of the text. Length is a positive number or zero to represent
the empty string.
- `{text_value}` is a sequence of bytes representing the string value in UTF8 encoding.

Example values

- `C3 00 00 00 03 61 62 63`: the string 'abc'.
- `C3 00 00 00 04 61 62 63 64`: the string 'abcd'.
- `C3 00 00 00 00`: the empty string ''.

==== 16-bit List

An ordered collection of items. The format depends on the {value_flag}.

Format: `{item_0}...{item_n}`

Where:

- `{item_0}...{item_n}` are the items of the list. `{item_i}` is a fully qualified typed value composed of
`{type_code}{type_size}{value}`.

==== 16-bit BulkedList

Format: `{item_0}{bulk_0}...{item_n}{bulk_n}`

Where:

- `{item_0}...{item_n}` are the items of the list. `{item_i}` is a fully qualified typed value composed of
`{type_code}{type_size}{value}`.
- `{bulk_0}...{bulk_n}` are `Int` that represent how many times that item should be repeated in the expanded list.

==== DateTime

A date-time with an offset from UTC/Greenwich in the ISO-8601 calendar system, such as 2007-12-03T10:15:30+01:00.

Format: `{0}{year}{1}{month}{2}{day}{3}{time}{4}{offset}`

Where:

- `{0}` is the byte `0x00`.
- `{year}` is an `Int` from -999,999,999 to 999,999,999.
- `{1}` is the byte `0x01`.
- `{month}` is a `Byte` to represent the month, from 1 (January) to 12 (December)
- `{2}` is the byte `0x02`.
- `{day}` is a `Byte` from 1 to 31.
- `{3}` is the byte `0x03`.
- `{time}` is a `Long` to represent nanoseconds since midnight, from 0 to 86399999999999
- `{4}` is the byte `0x04`.
- `{offset}` is an `Int` to represent total zone offset in seconds, from -64800 (-18:00) to 64800 (+18:00).
