FROM tinkerpop/gremlin-server:4.0.0-beta.2
COPY gremlin-server-dart.yaml /opt/gremlin-server/conf/gremlin-server-dart.yaml
COPY tinkergraph-service.properties /opt/gremlin-server/conf/tinkergraph-service.properties
COPY load-test-graphs.groovy /opt/gremlin-server/scripts/load-test-graphs.groovy
