host: 0.0.0.0
port: 45940
evaluationTimeout: 30000
channelizer: org.apache.tinkerpop.gremlin.server.channel.HttpChannelizer
graphs: {
  graph: conf/tinkergraph-service.properties,
  modern: conf/tinkergraph-service.properties,
  classic: conf/tinkergraph-service.properties,
  crew: conf/tinkergraph-service.properties,
  grateful: conf/tinkergraph-service.properties,
  sink: conf/tinkergraph-service.properties}
scriptEngines: {
  gremlin-lang: {},
  gremlin-groovy: {
    plugins: {
      org.apache.tinkerpop.gremlin.server.jsr223.GremlinServerGremlinPlugin: {},
      org.apache.tinkerpop.gremlin.tinkergraph.jsr223.TinkerGraphGremlinPlugin: {},
      org.apache.tinkerpop.gremlin.jsr223.ScriptFileGremlinPlugin: {
        files: [scripts/load-test-graphs.groovy]}}}}
serializers:
  - { className: org.apache.tinkerpop.gremlin.util.ser.GraphSONMessageSerializerV4 }
  - { className: org.apache.tinkerpop.gremlin.util.ser.GraphBinaryMessageSerializerV4 }
  - { className: org.apache.tinkerpop.gremlin.util.ser.GraphBinaryMessageSerializerV4, config: { serializeResultToString: true }}
metrics: {
  slf4jReporter: {enabled: true, interval: 180000}}
gremlinPool: 8
strictTransactionManagement: false
resultIterationBatchSize: 64
