select DISTINCT ?vendor
  where {
                  {
                          ?vendor v:type "vendor".
                          ?vendor v:country ?country.
                          FILTER (?country = 'RU').
                  } UNION
                  {
                          ?vendor v:type "vendor".
                          ?vendor v:country ?country.
                          FILTER (?country = 'GB').
                  }
  }
