////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at

  http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
////
== TinkerPop 3.8.2

*Release Date: NOT OFFICIALLY RELEASED YET*

Please see the link:https://github.com/apache/tinkerpop/blob/3.8.2/CHANGELOG.asciidoc#release-3-8-2[changelog] for a
complete list of all the modifications that are part of this release.

=== Upgrading for Users

==== Building and Running with JDK 25

TinkerPop can now be built and run with Java 25, in addition to the existing support for Java 11 and Java 17. Supporting
Java 25 required an upgrade of Groovy to 4.0.32, which bundles a version of ASM that is able to parse Java 25 bytecode
(class file version 69). The build's Java version enforcement was relaxed accordingly to permit Java 11 through Java 25.

As is the case with Java 17, some libraries still rely on deep reflection (most notably the Kryo serialization library
that is used with OLAP), so it may be necessary to `--add-opens` or `--add-exports` certain modules to run on Java 25.
The same set of options documented for JDK 17 applies to JDK 25 and is used by TinkerPop's own automated tests.

To support Java 25, Hadoop was upgraded from 3.3.3 to 3.4.3, which migrated off the removed Security Manager APIs (most
notably `Subject.getSubject()`, which no longer functions on Java 25). As a result the `hadoop-gremlin` module now
builds and runs on Java 25 as well.

The `spark-gremlin` module is not yet supported on Java 25. The only Spark releases that support Java 25 (Spark 4.1 and
later) require Java 17 as a minimum and Scala 2.13, which would drop Java 11 support for that module. `spark-gremlin`
therefore continues to target Spark 3.3.x and is built and tested with Java 11 and Java 17 only; it is excluded from the
Java 25 build.
