////
Licensed to the Apache Software Foundation (ASF) under one or more
contributor license agreements.  See the NOTICE file distributed with
this work for additional information regarding copyright ownership.
The ASF licenses this file to You under the Apache License, Version 2.0
(the "License"); you may not use this file except in compliance with
the License.  You may obtain a copy of the License at

  http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
////
= Simple TinkerPop Application

This is a simple starter project that demonstrates how a basic TinkerPop project is structured with Maven. This project
uses link:http://tinkerpop.apache.org/docs/${project.version}/reference/#tinkergraph-gremlin[TinkerGraph] as an
embedded graph database, loads it with some data and then executes a shortest path calculation, printing the results.

== Prerequisites

* Java 11
* link:https://maven.apache.org/[Maven 3.3+]

== Building and Running

[source,text]
mvn clean package
mvn exec:java -Dexec.mainClass="${package}.App"
